export const Data=[
    {
        name:'Title',
        url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUZWqEtuditcxs0HGlk-RPfBb__ytcy63A2xKrWbPN_q7CMdpV_-ZhqmT4W_tf4vrEKRQ&usqp=CAU'
    },
    {
        name:'Title2',
        url:'https://images.unsplash.com/photo-1598755257130-c2aaca1f061c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8d2lsZCUyMGFuaW1hbHxlbnwwfHwwfHw%3D&w=1000&q=80'
    },
    {
        name:'Title2',
        url:'https://res.cloudinary.com/dk-find-out/image/upload/q_80,c_limit,h_840,w_1240,f_auto/GettyImages_150644751_qknq07.png'
    },
    {
        name:'Title',
        url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjGZeGigf9vkVR-YreVENETvl2qEyaulGoGQ&usqp=CAU'
    },
    {
        name:'Title2',
        url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpzpeocx-X-AF0_Hs20J8PlE-_2vZIqM7sUw&usqp=CAU'
    },{
        name:'Title2',
        url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxOw9CCyK6g6ADDlrym0aupn8WWbfrHHe9n_Wdgvl9Ga2hJjiRvYC5z70wbXPCnu-4WHo&usqp=CAU'
    },
    {
        name:'Title2',
        url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGr6jdbYF-2ucZPMPNq8cDGxsrCpMQl1pDxA&usqp=CAU'
    },
    {
        name:'Title2',
        url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeM-IvG2byg4sUSXszrwAksoNqecYL_Pn9kA&usqp=CAU'
    },
    {
        name:'Title2',
        url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2IXV2dVNe0RwlvrmviGrUE61D2o0_wZPUwA&usqp=CAU'
    },
    {
        name:'Title2',
        url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSusYvItnzbIrW3eMEBNqlzg9cvWEOHm4v1Q&usqp=CAU'
    }
]
export default Data;